version: '3.7'
services:
  ## --------------------------- ORION --------------------------- ##

  chatwoot_app:
    image: ghcr.io/ever-sync/stravox:latest ## Versão do Chatwoot
    command: >
      sh -c "echo 'Rails.application.config.active_storage.variant_processor = :mini_magick' > /app/config/initializers/active_storage.rb && bundle exec rails s -p 3000 -b 0.0.0.0"
    entrypoint: docker/entrypoints/rails.sh
    volumes:
      - chatwoot_storage:/app/storage ## Arquivos de conversa
      - chatwoot_public:/app/public ## Arquivos de logos
      - chatwoot_mailer:/app/app/views/devise/mailer ## Arquivos de email
      - chatwoot_mailers:/app/app/views/mailers ## Arquivos de emails

    networks:
      - pluwisenet ## Nome da rede interna

    environment:
      ## 🌐 Qualquer Url com # no final
      #- CHATWOOT_HUB_URL=https://oriondesign.art.br/setup#

      ## 🏢 Nome da Empresa
      - INSTALLATION_NAME=pluwiseserv

      ## 🔐 Secret key
      - SECRET_KEY_BASE=<YOUR_SECRET_KEY_BASE>

      ## 💬 Url Chatwoot
      - FRONTEND_URL=https://woot.eversync.com.br
      - FORCE_SSL=true

      ## 🌍 Idioma/Localização padrão
      - DEFAULT_LOCALE=pt_BR
      - TZ=America/Sao_Paulo

      ## ☁️ Google Cloud - Modifique de acordo com os seus dados
      - GOOGLE_OAUTH_CLIENT_ID=<YOUR_GOOGLE_OAUTH_CLIENT_ID>
      - GOOGLE_OAUTH_CLIENT_SECRET=<YOUR_GOOGLE_OAUTH_CLIENT_SECRET>
      - GOOGLE_OAUTH_CALLBACK_URL=https://woot.eversync.com.br/omniauth/google_oauth2/callback

      ## 🔐 Facebook e Instagram
      - IG_VERIFY_TOKEN=<YOUR_IG_VERIFY_TOKEN>
      - FB_VERIFY_TOKEN=<YOUR_FB_VERIFY_TOKEN>
      - FB_APP_SECRET=<YOUR_FB_APP_SECRET>
      - FB_APP_ID=24208735642154651

      ## 🧑‍💻 Dados do Redis
      - REDIS_URL=redis://chatwoot_redis:6379

      ## 🗄️ Dados do Postgres
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=<YOUR_POSTGRES_PASSWORD> ## Senha do postgres
      - POSTGRES_DATABASE=chatwoot

      ## 🏠 Armazenamento
      - ACTIVE_STORAGE_SERVICE=local ## use s3_compatible para MinIO
      #- STORAGE_BUCKET_NAME=chatwoot
      #- STORAGE_ACCESS_KEY_ID=ACCESS_KEY_MINIO
      #- STORAGE_SECRET_ACCESS_KEY=SECRET_KEY_MINIO
      #- STORAGE_REGION=eu-south
      #- STORAGE_ENDPOINT=https://s3.DOMINIO.COM
      #- STORAGE_FORCE_PATH_STYLE=true

      ## 📧 Dados do SMTP
      - MAILER_SENDER_EMAIL=contato@eversync.com.br <contato@eversync.com.br> ## Email SMTP
      - SMTP_DOMAIN=eversync.com.br ## Dominio do email
      - SMTP_ADDRESS=smtp.hostinger.com ## Host SMTP
      - SMTP_PORT=465 ## Porta SMTP
      - SMTP_SSL=true ## Se a porta for 465 = true | Se a porta for 587 = false
      - SMTP_USERNAME=contato@eversync.com.br ## Usuario SMTP
      - SMTP_PASSWORD=<YOUR_SMTP_PASSWORD> ## Senha do SMTP
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=contato@eversync.com.br ## Email SMTP

      ## ⚙️ Melhorias
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false

      ## ⚡ Outras configurações
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot_app.rule=Host(`woot.eversync.com.br`)
        - traefik.http.routers.chatwoot_app.entrypoints=websecure
        - traefik.http.routers.chatwoot_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.chatwoot_app.priority=1
        - traefik.http.routers.chatwoot_app.service=chatwoot_app
        - traefik.http.services.chatwoot_app.loadbalancer.server.port=3000
        - traefik.http.services.chatwoot_app.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot_app.middlewares=sslheader

  ## --------------------------- ORION --------------------------- ##

  chatwoot_sidekiq:
    image: ghcr.io/ever-sync/stravox:latest ## Versão do Chatwoot
    command: bundle exec sidekiq -C config/sidekiq.yml

    volumes:
      - chatwoot_storage:/app/storage ## Arquivos de conversa
      - chatwoot_public:/app/public ## Arquivos de logos
      - chatwoot_mailer:/app/app/views/devise/mailer ## Arquivos de email
      - chatwoot_mailers:/app/app/views/mailers ## Arquivos de emails

    networks:
      - pluwisenet ## Nome da rede interna

    environment:
      ## 🌐 Qualquer Url com # no final
      #- CHATWOOT_HUB_URL=https://oriondesign.art.br/setup#

      ## 🏢 Nome da Empresa
      - INSTALLATION_NAME=pluwiseserv

      ## 🔐 Secret key
      - SECRET_KEY_BASE=<YOUR_SECRET_KEY_BASE>

      ## 💬 Url Chatwoot
      - FRONTEND_URL=https://woot.eversync.com.br
      - FORCE_SSL=true

      ## 🌍 Idioma/Localização padrão
      - DEFAULT_LOCALE=pt_BR
      - TZ=America/Sao_Paulo

      ## ☁️ Google Cloud - Modifique de acordo com os seus dados
      - GOOGLE_OAUTH_CLIENT_ID=<YOUR_GOOGLE_OAUTH_CLIENT_ID>
      - GOOGLE_OAUTH_CLIENT_SECRET=<YOUR_GOOGLE_OAUTH_CLIENT_SECRET>
      - GOOGLE_OAUTH_CALLBACK_URL=https://woot.eversync.com.br/omniauth/google_oauth2/callback

      ## 🔐 Facebook e Instagram
      - IG_VERIFY_TOKEN=<YOUR_IG_VERIFY_TOKEN>
      - FB_VERIFY_TOKEN=<YOUR_FB_VERIFY_TOKEN>
      - FB_APP_SECRET=<YOUR_FB_APP_SECRET>
      - FB_APP_ID=24208735642154651

      ## 🧑‍💻 Dados do Redis
      - REDIS_URL=redis://chatwoot_redis:6379

      ## 🗄️ Dados do Postgres
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=<YOUR_POSTGRES_PASSWORD> ## Senha do postgres
      - POSTGRES_DATABASE=chatwoot

      ## 🏠 Armazenamento
      - ACTIVE_STORAGE_SERVICE=local ## use s3_compatible para MinIO
      #- STORAGE_BUCKET_NAME=chatwoot
      #- STORAGE_ACCESS_KEY_ID=ACCESS_KEY_MINIO
      #- STORAGE_SECRET_ACCESS_KEY=SECRET_KEY_MINIO
      #- STORAGE_REGION=eu-south
      #- STORAGE_ENDPOINT=https://s3.DOMINIO.COM
      #- STORAGE_FORCE_PATH_STYLE=true

      ## 📧 Dados do SMTP
      - MAILER_SENDER_EMAIL=contato@eversync.com.br <contato@eversync.com.br> ## Email SMTP
      - SMTP_DOMAIN=eversync.com.br ## Dominio do email
      - SMTP_ADDRESS=smtp.hostinger.com ## Host SMTP
      - SMTP_PORT=465 ## Porta SMTP
      - SMTP_SSL=true ## Se a porta for 465 = true | Se a porta for 587 = false
      - SMTP_USERNAME=contato@eversync.com.br ## Usuario SMTP
      - SMTP_PASSWORD=<YOUR_SMTP_PASSWORD> ## Senha do SMTP
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=contato@eversync.com.br ## Email SMTP

      ## ⚙️ Melhorias
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false

      ## ⚡ Outras configurações
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=true

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M

  ## --------------------------- ORION --------------------------- ##

  chatwoot_redis:
    image: redis:latest ## Versão do Redis
    command: ['redis-server', '--appendonly', 'yes', '--port', '6379']

    volumes:
      - chatwoot_redis:/data

    networks:
      - pluwisenet ## Nome da rede interna

    ## Descomente as linhas abaixo para uso externo
    #ports:
    #  - 6379:6379

    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M

## --------------------------- ORION --------------------------- ##

volumes:
  chatwoot_storage:
    external: true
    name: chatwoot_storage
  chatwoot_public:
    external: true
    name: chatwoot_public
  chatwoot_mailer:
    external: true
    name: chatwoot_mailer
  chatwoot_mailers:
    external: true
    name: chatwoot_mailers
  chatwoot_redis:
    external: true
    name: chatwoot_redis

networks:
  pluwisenet: ## Nome da rede interna
    external: true
    name: pluwisenet ## Nome da rede interna
