export const STRAVOX_SET_USER = 'STRAVOX_SET_USER';
export const STRAVOX_RESET = 'STRAVOX_RESET';

export const ANALYTICS_IDENTITY = 'ANALYTICS_IDENTITY';
export const ANALYTICS_RESET = 'ANALYTICS_RESET';
